development:
  adapter: postgresql
  encoding: unicode
  database: tutorias_development
  pool: 5
  username: tutorias
  password: tutorias

test:
  adapter: postgresql
  encoding: unicode
  database: tutorias_test
  pool: 5
  username: tutorias
  password: tutorias